### ISSUE TITLE
Connection Error 

### ISSUE THREAD

**Issue by ptbr45** [PlaidSystems/Spruce_Gen1-SmartThings#5]
When I try to use this v2.6 code I get an error on my android phone smartthings app that says "We're having trouble conencting.  Check your network connection and try again."  I am sure my network connection is good--all other connected apps are working fine.

Any thoughts how to resolve?  Anything I can do to help resolve?

**Comment by natec007** [comment]
@ptbr45 code updated.
The device handler has been replaced with a variation of the ST released version.  Minor change to accommodate the updated Scheduler.  The Scheduler SST has been updated to use the proper commands to work with the updated device handler.  Try updating and it should all be working.

**Comment by ptbr45** [comment]
Well, it isn't. So what do I do now?Sent via the Samsung Galaxy S21 5G, an AT&T 5G smartphone
-------- Original message --------From: natec007 ***@***.***> Date: 5/18/21  11:27 AM  (GMT-06:00) To: PlaidSystems/Spruce_Gen1-SmartThings ***@***.***> Cc: ptbr45 ***@***.***>, Mention ***@***.***> Subject: Re: [PlaidSystems/Spruce_Gen1-SmartThings] Connection Error  (#5) 
@ptbr45 code updated.
The device handler has been replaced with a variation of the ST released version.  Minor change to accommodate the updated Scheduler.  The Scheduler SST has been updated to use the proper commands to work with the updated device handler.  Try updating and it should all be working.

**Comment by natec007** [comment]
Hello @ptbr45, I am not sure I understand.  The IDE code will need to be updated, and the controller removed and re-connected.  Is there other details that would help us understand as we don't see any connection problems.

In the SmartThings IDE, you can use the "Update from Repo" button to pull in the changes to your local code.

**Comment by ptbr45** [comment]
Ok, I am not sure what happened but when I updated the SST app and checked the device handlers again and then restarted the Pp again, it worked.  So it appears it works now.If I have any further issues I will follow up.  Thanks for your help.-PaulSent via the Samsung Galaxy S21 5G
-------- Original message --------From: natec007 ***@***.***> Date: 5/18/21  5:15 PM  (GMT-06:00) To: PlaidSystems/Spruce_Gen1-SmartThings ***@***.***> Cc: ptbr45 ***@***.***>, Mention ***@***.***> Subject: Re: [PlaidSystems/Spruce_Gen1-SmartThings] Connection Error  (#5) 
Hello @ptbr45, I am not sure I understand.  The IDE code will need to be updated, and the controller removed and re-connected.  Is there other details that would help us understand as we don't see any connection problems.

**Comment by natec007** [comment]
Great!  There is caching in the new app that causes much frustration in the ST developer forum and likely what happened.

**Comment by natec007** [comment]
Updated device and scheduler
